# Generated by Django 5.1.1 on 2024-09-08 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(help_text='Unique Product ID, same across databases', max_length=64, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Product Name', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Product Price', max_digits=10)),
                ('description', models.TextField(help_text='Product Description')),
                ('image', models.ImageField(help_text='Product Image', null=True, upload_to='product_images')),
                ('physicalStock', models.PositiveIntegerField(help_text='Product Physical Stock', null=True)),
                ('reservedStock', models.PositiveIntegerField(default=0, help_text='Product Reserved Stock', null=True)),
                ('rawAvailability', models.BinaryField(default=None, help_text='Product Availability Configuration', null=True)),
                ('notes', models.TextField(default=None, help_text='Product Notes', max_length=500, null=True)),
                ('tags', models.JSONField(default=None, help_text='Product Tags', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(help_text='Unique Log ID, same across databases', primary_key=True, serialize=False)),
                ('logType', models.CharField(choices=[('Debug', 'D'), ('Info', 'I'), ('Warning', 'W'), ('Error', 'E'), ('Critical', 'C')], help_text='Log Type', max_length=8)),
                ('logMessage', models.TextField(help_text='Log Message', max_length=500)),
                ('origin', models.CharField(default=None, help_text='Log Origin', max_length=500, null=True)),
                ('exceptionObject', models.BinaryField(default=None, help_text='Exception', null=True)),
                ('additionalData', models.JSONField(default=None, help_text='Additional Data', null=True)),
                ('logTime', models.DateTimeField(auto_now_add=True, help_text='Log Time')),
                ('logUser', models.ForeignKey(default=-1, help_text='User', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(editable=False, help_text='Unique Order ID, same across databases', max_length=64, primary_key=True, serialize=False, unique=True)),
                ('orderTime', models.DateTimeField(auto_now_add=True, help_text='Order Time')),
                ('totalCost', models.DecimalField(decimal_places=2, help_text='Order Total', max_digits=10, null=True)),
                ('notes', models.TextField(default=None, help_text='Order Notes', max_length=500, null=True)),
                ('user', models.ForeignKey(help_text='User ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.CharField(help_text='Unique OrderLine ID, same across databases', max_length=64, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity')),
                ('quantityReserved', models.PositiveIntegerField(default=0, help_text='Quantity Reserved')),
                ('persistentCost', models.DecimalField(decimal_places=2, help_text='Persistent Cost', max_digits=10)),
                ('itemCost', models.DecimalField(decimal_places=2, default=0, help_text='Total Cost', max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'P'), ('Open', 'O'), ('Waiting_for_Balance', 'W'), ('Confirmed', 'C'), ('In_Production', 'I'), ('Delivered', 'D'), ('Returned', 'R'), ('Cancelled', 'X'), ('Locked', 'L'), ('Standing_by_for_Stock', 'S')], default='P', help_text='Order Status', max_length=21, null=True)),
                ('statusInformation', models.TextField(default=None, help_text='Status Information', max_length=500, null=True)),
                ('notes', models.TextField(default=None, help_text='Order Line Notes', max_length=500, null=True)),
                ('availabilityID', models.IntegerField(default=-1, help_text='ID of Stock Configuration used in linked Product for availability', null=True)),
                ('linkedOrder', models.ForeignKey(default=-1, help_text='Order ID', on_delete=django.db.models.deletion.CASCADE, to='candb.order')),
                ('linkedProduct', models.ForeignKey(default=-1, help_text='Product ID', on_delete=django.db.models.deletion.CASCADE, to='candb.product')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
