# Generated by Django 5.1.1 on 2024-11-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='availabilityIDs',
        ),
        migrations.AddField(
            model_name='orderline',
            name='stockContributions',
            field=models.JSONField(default=None, help_text='ID of Stock Configurations used in linked Product for availability', null=True),
        ),
    ]
