# Generated by Django 5.1.1 on 2024-11-27 05:15

import candb.models
import concurrency.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candb', '0002_remove_orderline_availabilityids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='_saveVersion',
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.CharField(help_text='Unique Vendor ID', max_length=43, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Vendor Name', max_length=100)),
                ('_saveVersion', concurrency.fields.IntegerVersionField(default=0, help_text='Save Version for Concurrency Control')),
                ('vendorAdmin', models.ForeignKey(help_text='Administrator account for vendor', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'db_table_comment': 'Vendors',
                'permissions': [('view_any_vendor', 'Can view all vendors'), ('change_any_vendor', 'Can change any vendor configuration'), ('delete_any_vendor', 'Can delete any vendor'), ('create_any_vendor', 'Can create any vendor and assign it to any administrator')],
            },
        ),
        migrations.CreateModel(
            name='StockConfig',
            fields=[
                ('id', models.CharField(help_text='Unique Stock Configuration ID, same across databases', max_length=42, primary_key=True, serialize=False, unique=True)),
                ('available', models.BooleanField(help_text='Product Availability')),
                ('useModelStock', models.BooleanField(blank=True, help_text='Use Model Stock')),
                ('infinite', models.BooleanField(blank=True, help_text='Infinite Stock')),
                ('physicalStock', models.PositiveIntegerField(blank=True, help_text='Physical Stock')),
                ('remainingStock', models.PositiveIntegerField(blank=True, help_text='Remaining Stock')),
                ('_saveVersion', concurrency.fields.IntegerVersionField(default=0, help_text='Save Version for Concurrency Control')),
                ('reference', models.ForeignKey(blank=True, help_text='Reference to another Stock Configuration', on_delete=django.db.models.deletion.CASCADE, to='candb.stockconfig')),
                ('vendor', models.ForeignKey(help_text='Vendor ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='candb.vendor')),
            ],
            options={
                'verbose_name': 'Stock Configuration',
                'verbose_name_plural': 'Stock Configurations',
                'db_table_comment': 'Stock Configurations',
                'permissions': [('view_any_configuration', 'Can view all stock configurations'), ('change_any_configuration', 'Can change any stock configuration regardless of its vendor'), ('delete_any_configuration', 'Can delete any stock configurations regardless of its vendor'), ('add_any_configuration', 'Can add stock configurations and assign it to any owner')],
            },
        ),
        migrations.CreateModel(
            name='TimeBracket',
            fields=[
                ('id', models.CharField(help_text='Unique Time Bracket ID, same across databases', max_length=44, primary_key=True, serialize=False, unique=True)),
                ('bracketType', models.PositiveSmallIntegerField(choices=[(1, 'Datetime'), (2, 'Weekday'), (0, 'Default')], help_text='Format type for Bracket')),
                ('priority', models.PositiveSmallIntegerField(blank=True, help_text='Priority for Bracket', null=True)),
                ('startDatetime', models.DateTimeField(blank=True, help_text='When bracketType is DATETIME, this is the start datetime for the bracket.', null=True)),
                ('endDatetime', models.DateTimeField(blank=True, help_text='When bracketType is DATETIME, this is the end datetime for the bracket.', null=True)),
                ('applicableWeekdays', candb.models.IntegerSet(blank=True, help_text='When bracketType is WEEKDAY, this is a set of weekdays which the bracket applies for.', null=True)),
                ('_saveVersion', concurrency.fields.IntegerVersionField(default=0, help_text='Save Version for Concurrency Control')),
                ('linkedProduct', models.ForeignKey(help_text='Linked Product which Bracket Applies To', on_delete=django.db.models.deletion.CASCADE, to='candb.product')),
                ('linkedStockConfig', models.ForeignKey(help_text='Linked Stock Configuration which applies to time bracket', on_delete=django.db.models.deletion.PROTECT, to='candb.stockconfig')),
            ],
            options={
                'verbose_name': 'Time Bracket',
                'verbose_name_plural': 'Time Brackets',
                'db_table_comment': 'Time Bracket for Stock Configurations',
                'permissions': [('view_any_bracket', 'Can view all brackets'), ('change_any_bracket', 'Can change any time bracket regardless of its vendor'), ('delete_any_bracket', 'Can delete any time bracket regardless of its vendor'), ('add_any_bracket', 'Can add time brackets and assign it to any vendor')],
                'indexes': [models.Index(fields=['id', 'linkedProduct'], name='CanDB_TimeBracket_Index')],
                'constraints': [models.CheckConstraint(condition=models.Q(('id__startswith', 'BRACKET-')), name='CanDB_Bracket_ID_Prefix', violation_error_code='TIMEBRACKET-ID-1', violation_error_message="Time Bracket ID must start with 'BRACKET-'"), models.CheckConstraint(condition=models.Q(('id__len', 44)), name='CanDB_Bracket_ID_Len', violation_error_code='TIMEBRACKET-ID-2', violation_error_message='Time Bracket ID must be 44 characters long')],
            },
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['id', 'name'], name='CanDB_Vendor_Index'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.CheckConstraint(condition=models.Q(('id__startswith', 'VENDOR-')), name='CanDB_Vendor_ID_Prefix', violation_error_code='VENDOR-ID-1', violation_error_message="Vendor ID must start with 'VENDOR-'"),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.CheckConstraint(condition=models.Q(('id__len', 43)), name='CanDB_Vendor_ID_Len', violation_error_code='VENDOR-ID-2', violation_error_message='Vendor ID must be 43 characters long'),
        ),
        migrations.AddIndex(
            model_name='stockconfig',
            index=models.Index(fields=['id'], name='CanDB_StockConfig_ID_Index'),
        ),
        migrations.AddConstraint(
            model_name='stockconfig',
            constraint=models.CheckConstraint(condition=models.Q(('id__startswith', 'STOCK-')), name='CanDB_StockConfig_ID_Prefix', violation_error_code='STOCKCONFIG-ID-1', violation_error_message="Stock Configuration ID must start with 'STOCK-'"),
        ),
        migrations.AddConstraint(
            model_name='stockconfig',
            constraint=models.CheckConstraint(condition=models.Q(('id__len', 42)), name='CanDB_StockConfig_ID_Len', violation_error_code='STOCKCONFIG-ID-2', violation_error_message='Stock Configuration ID must be 42 characters long'),
        ),
        migrations.AddConstraint(
            model_name='stockconfig',
            constraint=models.CheckConstraint(condition=models.Q(('physicalStock__isnull', True), models.Q(('remainingStock__isnull', True), _negated=True)), name='CanDB_StockConfig_Physical_Null_But_Not_Remaining_Null', violation_error_code='STOCKCONFIG-STOCK-1', violation_error_message='If physical stock is None, reserved stock must be None'),
        ),
        migrations.AddConstraint(
            model_name='stockconfig',
            constraint=models.CheckConstraint(condition=models.Q(('remainingStock__lte', models.F('physicalStock'))), name='CanDB_StockConfig_Stock_Remaining', violation_error_code='STOCKCONFIG-STOCK-2', violation_error_message='Remaining stock must be smaller or equal to physical stock'),
        ),
    ]
