# Generated by Django 5.1.1 on 2024-10-04 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candb', '0002_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-orderTime', 'id'], 'permissions': [('view_all_orders', 'Can view orders regardless of its owner'), ('change_any_order', 'Can change any orders regardless of its owner'), ('delete_any_order', 'Can delete orders regardless of its owner'), ('add_any_order', 'Can add any order regardless of its owner'), ('change_any_order_but_overridecost', 'Can change orders regardless of its owner, but cannot override the cost')], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderline',
            options={'ordering': ['id'], 'permissions': [('view_any_orderline', 'Can view any orderline regardless of its owner'), ('change_any_orderline', 'Can change any orderlines regardless of its owner'), ('change_any_orderline_but_forceprice', 'Can change any orderlines regardless of its owner, but cannot force a price'), ('delete_any_orderline', 'Can delete any orderlines regardless of its owner'), ('add_any_orderline', 'Can add orderlines regardless of its owner')], 'verbose_name': 'OrderLine', 'verbose_name_plural': 'OrderLines'},
        ),
    ]
