# Generated by Django 5.1.1 on 2024-10-05 05:34

import candb.common
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candb', '0003_alter_order_options_alter_orderline_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='adminNotes',
            field=models.TextField(default=None, help_text='Admin Notes', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='User Balance', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.JSONField(decoder=candb.common.DateTimeDecoder, default=None, encoder=candb.common.DateTimeEncoder, help_text='Product Availability Configuration', null=True),
        ),
    ]
