# Generated by Django 5.1.1 on 2024-11-27 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candb', '0003_remove_order__saveversion_vendor_stockconfig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timebracket',
            name='linkedProduct',
            field=models.ForeignKey(help_text='Linked Product which Bracket Applies To', null=True, on_delete=django.db.models.deletion.CASCADE, to='candb.product'),
        ),
        migrations.AlterField(
            model_name='timebracket',
            name='linkedStockConfig',
            field=models.ForeignKey(help_text='Linked Stock Configuration which applies to time bracket', null=True, on_delete=django.db.models.deletion.PROTECT, to='candb.stockconfig'),
        ),
    ]
