# Generated by Django 5.1.1 on 2024-10-05 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candb', '0004_profile_adminnotes_profile_balance_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_old',
        ),
    ]
