# Generated by Django 5.1.1 on 2024-11-27 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candb', '0004_alter_timebracket_linkedproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockconfig',
            name='available',
            field=models.BooleanField(blank=True, help_text='Product Availability', null=True),
        ),
        migrations.AlterField(
            model_name='stockconfig',
            name='infinite',
            field=models.BooleanField(blank=True, help_text='Infinite Stock', null=True),
        ),
        migrations.AlterField(
            model_name='stockconfig',
            name='physicalStock',
            field=models.PositiveIntegerField(blank=True, help_text='Physical Stock', null=True),
        ),
        migrations.AlterField(
            model_name='stockconfig',
            name='reference',
            field=models.ForeignKey(blank=True, help_text='Reference to another Stock Configuration', null=True, on_delete=django.db.models.deletion.CASCADE, to='candb.stockconfig'),
        ),
        migrations.AlterField(
            model_name='stockconfig',
            name='remainingStock',
            field=models.PositiveIntegerField(blank=True, help_text='Remaining Stock', null=True),
        ),
        migrations.AlterField(
            model_name='stockconfig',
            name='useModelStock',
            field=models.BooleanField(blank=True, help_text='Use Model Stock', null=True),
        ),
        migrations.AlterField(
            model_name='stockconfig',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Vendor ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='candb.vendor'),
        ),
    ]
