# Generated by Django 5.1.1 on 2024-10-06 05:58

import concurrency.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candb', '0005_delete_product_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='_saveVersion',
            field=concurrency.fields.IntegerVersionField(default=0, help_text='Save Version for Concurrency Control'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='_saveVersion',
            field=concurrency.fields.IntegerVersionField(default=0, help_text='Save Version for Concurrency Control'),
        ),
        migrations.AddField(
            model_name='product',
            name='_saveVersion',
            field=concurrency.fields.IntegerVersionField(default=0, help_text='Save Version for Concurrency Control'),
        ),
        migrations.AddField(
            model_name='profile',
            name='_saveVersion',
            field=concurrency.fields.IntegerVersionField(default=0, help_text='Save Version for Concurrency Control'),
        ),
    ]
