# Generated by Django 5.1.1 on 2024-11-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candb', '0005_alter_stockconfig_available_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockconfig',
            name='CanDB_StockConfig_Physical_Null_But_Not_Remaining_Null',
        ),
        migrations.AddConstraint(
            model_name='stockconfig',
            constraint=models.CheckConstraint(condition=models.Q(('physicalStock__isnull', True), ('remainingStock__isnull', True)), name='CanDB_StockConfig_Physical_Null_But_Not_Remaining_Null', violation_error_code='STOCKCONFIG-STOCK-1', violation_error_message='If physical stock is None, reserved stock must be None'),
        ),
    ]
