# Generated by Django 5.1.1 on 2024-11-27 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candb', '0006_remove_stockconfig_candb_stockconfig_physical_null_but_not_remaining_null_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockconfig',
            name='CanDB_StockConfig_Stock_Remaining',
        ),
        migrations.RemoveConstraint(
            model_name='stockconfig',
            name='CanDB_StockConfig_Physical_Null_But_Not_Remaining_Null',
        ),
    ]
