# Generated by Django 5.1.1 on 2024-11-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candb', '0007_remove_stockconfig_candb_stockconfig_stock_remaining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockconfig',
            name='available',
            field=models.BooleanField(default=True, help_text='Product Availability'),
        ),
    ]
