# Generated by Django 5.1.1 on 2024-12-09 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candb', '0008_alter_stockconfig_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timebracket',
            name='linkedProduct',
            field=models.ForeignKey(help_text='Linked Product which Bracket Applies To', on_delete=django.db.models.deletion.CASCADE, to='candb.product'),
        ),
        migrations.AlterField(
            model_name='timebracket',
            name='linkedStockConfig',
            field=models.ForeignKey(help_text='Linked Stock Configuration which applies to time bracket', on_delete=django.db.models.deletion.PROTECT, to='candb.stockconfig'),
        ),
    ]
